name: Build Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  review_pull_request_job:
    name: Run test cases
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Store cache
        uses: actions/checkout@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run detekt
        run: ./gradlew detekt

      - name: Run lint
        run: ./gradlew lint
