name: Build Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  review_pull_request_job:
    name: Run test cases
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Store cache
        uses: actions/checkout@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 --decode > ./app/google-services.json

      - name: Decode local properties
        run: echo ${{ secrets.LOCAL_PROPERTIES }} | base64 --decode > ./local.properties

      - name: Run detekt
        run: ./gradlew detekt

      - name: Run lint
        run: ./gradlew lint

      - name: Run unit test and Kover Coverage
        run: ./gradlew koverMergedXmlReport

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Bundle and check environment versions
        run: |
          echo 'Install Bundle'
          bundle config path vendor/bundle
          bundle install
          echo 'Check environment setup versions'
          ruby --version
          gem --version
          bundler --version

      - name: Run Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.BOT_API_TOKEN }}
        run: |
          bundle exec danger
