name: Build And Deploy App to Firebase Distribution

on:
  push:
    branches:
      - develop

jobs:
  build_and_release_job:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 --decode  --ignore-garbage > ./app/google-services.json

      - name: Decode local properties
        run: echo ${{ secrets.LOCAL_PROPERTIES }} | base64 --decode  --ignore-garbage > ./local.properties

      - name: build release
        run: ./gradlew assembleDevRelease

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: Debug
          file: app/build/outputs/apk/dev/release/app-dev-release-unsigned.apk
